### ISSUE TITLE
Bump tag-release to 1.0.3

### ISSUE THREAD

**Issue by ThomasTJdev** [euantorano/recaptcha.nim#4]
Current tag is 1.0.2 while installing from nimble. Needs to be tagged with 1.0.3 to include latest fix from  6e3d474a0b45c1015723e1c42553901628987869

**Comment by euantorano** [comment]
Good catch, will do that now, thanks!

**Comment by euantorano** [comment]
Fixed with tag [`v1.0.3`](https://github.com/euantorano/recaptcha.nim/releases/tag/v1.0.3).
